export const SAVE_MODEL = 'SAVE_MODEL';
export const SAVING_MODEL = 'SAVING_MODEL';
export const SAVED_MODEL = 'SAVED_MODEL';
export const FETCHING_MODELS = 'FETCHING_MODELS';
export const FETCHED_MODELS = 'FETCHED_MODELS';
